version: '3'
services:

  mysql:
    image: "mysql:8.0.30"
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

